# Generated by Django 4.1.7 on 2023-03-20 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagenes',
            name='carrousel',
        ),
        migrations.DeleteModel(
            name='Carrousel',
        ),
        migrations.DeleteModel(
            name='Imagenes',
        ),
    ]
